In [ ]:
import numpy as np

In [ ]:
ZeroD=np.array(46)
print(type(ZeroD))

<class 'numpy.ndarray'>


In [ ]:
OneD=np.array([10,20,30,40,50])
OneD

array([10, 20, 30, 40, 50])

In [ ]:
TwoD=np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
TwoD

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
ThreeD=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
ThreeD

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [ ]:
np.ndim(TwoD)

2

In [ ]:
np.size(TwoD)

20

In [ ]:
np.ndim(ThreeD)

3

In [ ]:
np.size(ThreeD)

12

In [ ]:
np.shape(TwoD)

(4, 5)

In [ ]:
np.shape(TwoD)

(4, 5)

In [ ]:
print(len(TwoD))

4


In [ ]:
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [ ]:
b.shape

(5,)

In [ ]:
b.reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [ ]:
b.argmax()

np.int64(4)

In [ ]:
b[3:]

array([7, 9])

In [ ]:
np.linspace(1,25,2)
#np.linspace(4,50,7)

array([ 1., 25.])

In [ ]:
np.random.rand(4,2)


array([[0.32154401, 0.38313062],
       [0.13575435, 0.86070739],
       [0.62181719, 0.54179369],
       [0.00474327, 0.14400023]])

In [ ]:
np.random.randint(1,5,10)

array([3, 4, 1, 3, 2, 3, 2, 1, 4, 1])

In [ ]:
np.unique(b)

array([1, 3, 5, 7, 9])